#!/bin/bash

profile=/profiles/de
rhasspy_weather=$(dirname "$(readlink -f "$0")")

pip3 install wheel
pip3 install -e $rhasspy_weather

python3 $rhasspy_weather/generate_slots.py -x $rhasspy_weather
chmod +x $rhasspy_weather/slot_programs/*
mkdir -p $profile/custom_command
ln -s $rhasspy_weather/custom_commands.py $profile/custom_command
slots=slot_programs/rhasspy_weather_slots
mkdir -p $profile/$slots
for f in $rhasspy_weather/slot_programs/*
do
	filename=$(basename $f)
	ln -s $rhasspy_weather/slot_programs/$filename $profile/$slots/$filename
done