#!/usr/bin/python3
import datetime
import logging
import os

import pytz

from rhasspy_weather.data_types.config import get_config

logging_format = '%(asctime)s - %(levelname)-5s - %(name)s.%(funcName)s[%(lineno)d]: %(message)s'
logging.basicConfig(filename=os.path.join(os.path.dirname(__file__), 'output.log'), format=logging_format, datefmt="%Y-%m-%d %H:%M:%S", level=logging.DEBUG)


def custom_time(*args):
    converted = datetime.datetime.now(pytz.timezone('Europe/Berlin'))
    return converted.timetuple()


logging.Formatter.converter = custom_time

config = get_config()

named_times = list(slot_programs.named_times.keys()) + list(config.locale.named_times_synonyms.keys())

for s in named_times:
    print(s)
