#!/usr/bin/python3
import datetime
import logging
import os
import sys

import pytz

sys.path.append(os.path.abspath(os.path.join(os.path.join(os.path.join(os.path.dirname(__file__), '..'), '..'), "custom_command")))
from rhasspy_weather.data_types.config import get_config

logging_format = '%(asctime)s - %(levelname)-5s - %(name)s.%(funcName)s[%(lineno)d]: %(message)s'
logging.basicConfig(filename=os.path.join(os.path.dirname(__file__), 'output.log'), format=logging_format, datefmt="%Y-%m-%d %H:%M:%S", level=logging.DEBUG)


def custom_time(*args):
    converted = datetime.datetime.now(pytz.timezone('Europe/Berlin'))
    return converted.timetuple()


logging.Formatter.converter = custom_time

config = get_config()

named_days = list(config.locale.named_days.keys()) + list(config.locale.named_days_synonyms.keys())

for s in named_days:
    print(s)
